[package]
name = "proto-build"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>", "Tony Arcieri <tony@iqlusion.io>"]
edition = "2018"
publish = false


[dependencies]
prost = "0.11"
prost-build = "0.11"
tonic = "0.9"
tonic-build = "0.8"
regex = "1"
walkdir = "2"
