[workspace]
resolver = "2"
members = [
    "proto-build",
    "cosmos-sdk-proto",
    "cosmrs"
]

[patch.crates-io]
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/missing-serde-proto" }
